### ISSUE TITLE
Can I use a foreach construct with future.mirai

### ISSUE THREAD

**Issue by statquant** [HenrikBengtsson/future.mirai#10]
Hello, 
I was planing to try moving to mirai, can I expect a  classic foreach to work using future.mirai ?
Many thanks for your work

**Comment by HenrikBengtsson** [comment]
Yes, all future backends work with **foreach** via the **doFuture** package

**Comment by HenrikBengtsson** [comment]
See <https://dofuture.futureverse.org/> for example. Just use `plan(mirai_multisession)` instead.
