### ISSUE TITLE
mirai interface updates

### ISSUE THREAD

**Issue by shikokuchuo** [HenrikBengtsson/future.mirai#3]
Great to finally see this Henrik!

Perhaps open discussions for easier discussion?

I have not had the chance to really look over yet, but should mention that the latest version of `mirai` has introduced a new dedicated function `status()` and deprecated the use of `daemons()` with no arguments.

Should I open PRs in case there are other things I notice, or should I give you some time to catch up first?

**Comment by HenrikBengtsson** [comment]
Hi. Thanks for letting me know. Yes, I'd be happy for a PR if you've got the cycles.

**Comment by shikokuchuo** [comment]
I'll have to find time to look over the package in full, so I've opened a PR just for the obvious changes. I will open new issues for other comments.

**Comment by HenrikBengtsson** [comment]
Thank you for this. Sorry for the latency. Merged.
